config/routes.rb
Project5::Application.routes.draw do
 
match '/signup', :to => 'users#new'
match '/contact', :to => 'pages#contact'
match '/about', :to => 'pages#about'
match '/help', :to => 'pages#help'
match '/', :to => 'pages#home'

root :to =>'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base

	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 


	validates :name, :presence => true, 
					 :length => { :maximum => 50}
	validates :email, :presence => true,
	                   :format => { :with => email_regex}, 
	                   :uniqueness => {:case_sensitive => false}
	validates :password, :presence => true, 
						 :confirmation => true, 
						 :length => {:within => 6..40}



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	@title = "Home"
  end

  def contact
  @title = "Contact"
  end

  def help
  	@title = "Help"
  end

  def about
  	@title = "About"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign up"
  end

  def show
  	@user =User.find(params: [:id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper


	#return a title on a per-page basis


	def title
		base_title = "Party Maneger"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{title}"
		end 
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>

<%= image_tag("logo.png", :alt => "party manager", :class => "round") %>

<nav class ="round">
<ul>

<li><%= link_to "about", about_path %> </li>
<li><%= link_to "contact", contact_path %> </li>

</ul>

</nav>
</footer>

app/views/layouts/_header.html.erb
<header>

<%= image_tag("logo.png", :alt => "party manager", :class => "round")%>

<nav class ="round">
<ul>
<li> <%= link_to "home", root_path %></li>
<li> <%= link_to "help", help_path %></li>
<li> <%= link_to "sign in", '#' %></li>

</ul>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= @title %> </title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" type="text/css" href="custom.css" />
  <%= csrf_meta_tag %>
</head>
<body>
<div class ="container">

	<%= render 'layouts/header'%>
	<section class ="round">
<%= yield %>

</section>
	<%= render 'layouts/footer'%>
	<% debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1> About </h1>
<p>
This is the about page, you can see a lot about us here :) 
</p>

app/views/pages/contact.html.erb
<html>
<head>
<title>Party Maneger |contact</title> 
</head>
<body>
	<h1> Party Manager</h1>
	<p>
		this is the contact page for the party manager
	</p>
</body>
</html>

app/views/pages/help.html.erb
<h1> Help </h1>
<p>
Get help on Ruby on Rails toturials at the ... see book online

</p>

app/views/pages/home.html.erb
<html>
<head>
	<title>Party Maneger |home </title>
</head>
<body>
	<h1> Party Manager</h1>
	<p>
		this is the home page for the party manager
	</p>

<%= link_to "sign up now", signup_path, :class => "signup_bottom round" %>

</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>